development: &default
  adapter: postgresql
  database: giftlist_development
  host: localhost
  port: <%= ENV['BOXEN_POSTGRESQL_PORT'] || 5432 %>
  encoding: utf8

test:
  <<: *default
  database: giftlist_test
